# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

# Use self hosted agent
pool:
  name: azure-container-apps-pool

steps:
- script: echo Getting AzDevOps pipelines busy!
  displayName: 'Run a one-line script'

- script: |
    echo 'Run something else for Azure Container Apps KEDA autoscaling to trigger...'
  displayName: 'Run something else for KEDA to auto-scale'
